// ─────────────────────────────────────────────────────────────────────────────
// THEME SYSTEM
// Every color used across the app is catalogued here as a token on the DEFAULT
// theme. The current look of the app is the DEFAULT theme. Adding a new theme is
// as simple as copying `defaultTheme`, overriding tokens, and registering it in
// the `themes` map + `THEME_NAMES` array below.
//
// NOTE: PNG background images in the top bar are intentionally NOT themed.
// ─────────────────────────────────────────────────────────────────────────────

export const defaultTheme = {
  name: 'DEFAULT',

  // ── App shell / page backgrounds ──────────────────────────────────────────
  bgApp:            '#0a1e30',
  bgAppMobile:      '#0a0f1a',
  bgPhone:          '#87bbd8',
  bgPage:           '#0a0f1a',
  bgStatusBar:      '#071624',
  bgTopBar:         '#071624',
  bgNav:            '#071624',
  bgScroll:         '#0a0f1a',

  // ── Cards / surfaces ──────────────────────────────────────────────────────
  bgCard:           '#0f2238',
  bgCardAlt:        '#0d1e30',
  bgSurface:        '#162d48',
  bgSurfaceRaised:  '#1e3a55',
  bgInput:          '#162d48',
  bgInputDark:      '#0d1e30',
  bgWeekCard:       '#0d1e30',
  bgTopBarWeek:     'rgba(10,15,26,0.95)',

  // ── Borders ───────────────────────────────────────────────────────────────
  borderDefault:    '#1e3a55',
  borderActive:     '#4a9adc',
  borderMuted:      '#1a3055',
  borderRaised:     '#2d4a6a',
  borderTopBar:     '#3a7ab8',
  borderPhone:      '#4a8ab8',

  // ── Text ──────────────────────────────────────────────────────────────────
  textPrimary:      '#f0f8ff',
  textSecondary:    '#8bbdd8',
  textMuted:        '#4a7a9a',
  textOnAccent:     '#fff',
  textHeading:      '#e0f0e0',
  textHeadingAlt:   '#e0f0ff',
  textBright:       '#ffffff',
  textBlack:        '#000',

  // ── Accents ───────────────────────────────────────────────────────────────
  accentGreen:      '#5adb9a',
  accentGreenBright:'#00ff88',
  accentGreenNeon:  '#7dff4f',
  accentGreenDark:  '#1d9e75',
  accentGreenDeep:  '#1d5a3a',
  accentGreenLogo:  '#39e07a',
  accentBlue:       '#4a9adc',
  accentBlueLight:  '#7dd8ff',
  accentBluePale:   '#c0e0f8',
  accentBlueSky:    '#4db8ff',
  accentBlueDeep:   '#1e5080',
  accentOrange:     '#ff6b4a',
  accentOrangeDark: '#e05a3a',
  accentOrangeAmber:'#ff9a40',
  accentOrangeGold: '#e8a030',
  accentRed:        '#cc2222',
  accentRedBright:  '#ff4444',
  accentRedDeep:    '#aa0000',
  accentRedSoft:    '#ff6666',
  accentPurple:     '#a878f0',
  accentPurpleLight:'#c8a8ff',
  accentPurpleDeep: '#6a3a9a',
  accentGold:       '#FFD700',
  accentGoldWarm:   '#ffd700',

  // ── Buttons ───────────────────────────────────────────────────────────────
  buttonFdeBg:       '#ff6b4a',
  buttonFdeBgHover:  '#e05a3a',
  buttonFdeText:     '#fff',
  buttonSecondaryBg: '#0f2238',
  buttonSecondaryText:'#8bbdd8',
  buttonGreenBg:     '#1d5a3a',
  buttonGreenText:   '#5adb9a',
  buttonGreenBorder: '#1d9e75',
  buttonSaveBg:      '#1a7a4a',

  // ── Nav ───────────────────────────────────────────────────────────────────
  navBg:            '#071624',
  navBorder:        '#3a7ab8',
  navInactive:      '#7aaec8',
  navHover:         '#c0e0f8',
  navActive:        '#7dff4f',
  navLabelColor:    'inherit',

  // ── Inputs ────────────────────────────────────────────────────────────────
  inputBg:          '#162d48',
  inputBorder:      '#1e3a55',
  inputText:        '#f0f8ff',
  inputBorderFocus: '#4a9adc',
  inputPlaceholder: '#4a7a9a',

  // ── Chips ─────────────────────────────────────────────────────────────────
  chipBg:           '#0f2238',
  chipBorder:       '#1e3a55',
  chipText:         '#8bbdd8',
  chipBorderHover:  '#4a9adc',
  chipTextHover:    '#c0e0f8',
  chipActiveBg:     '#1e3a55',
  chipActiveText:   '#c0e8ff',
  mchipActiveBg:    '#0d2a4a',

  // ── Stat boxes ────────────────────────────────────────────────────────────
  statBoxBg:        '#0f2238',
  statBoxVal:       '#ff6b4a',
  statBoxLbl:       '#8bbdd8',

  // ── Badges ────────────────────────────────────────────────────────────────
  badgeBg:          '#0d2a4a',
  badgeText:        '#5adb9a',
  badgeBorder:      '#1d9e75',
  prBadgeBg:        '#ff6b4a',
  prBadgeText:      '#fff',

  // ── Misc common ───────────────────────────────────────────────────────────
  flashText:        '#5adb9a',
  emptyText:        '#4a7a9a',
  dividerColor:     '#1e3a55',
  backBtn:          '#ff6b4a',
  sectionLabel:     '#8bbdd8',

  // ── Week screen ───────────────────────────────────────────────────────────
  weekBg:           '#0a0f1a',
  weekCard:         '#0d1e30',
  weekBorder:       '#1e3a55',
  dayPillBg:        '#0f2238',
  dayPillTodayBg:   '#2d5a9a',
  dayPillTodayBorder:'#4a9adc',
  dayPillTodayText: '#ffffff',
  dayLabel:         '#8bbdd8',
  dayNum:           '#c0d8f0',
  dayDot:           '#1d9e75',
  exRowBorder:      '#1a3055',
  exRowHover:       '#1e3a55',
  exName:           '#f0f8ff',
  exSub:            '#8bbdd8',
  circuitHeader:    '#6a9a4a',
  circuitLine:      '#3a6a1a',
  logTitle:         '#5adb9a',
  fieldLabel:       '#8bbdd8',
  prescribedDone:   '#3a7a5a',
  weekArrow:        '#6a9a6a',
  selectedDayBorder:'#7dff4f',

  // ── History screen ────────────────────────────────────────────────────────
  historyBg:        '#1a1408',
  historyStatusBg:  '#110e05',
  historyCardBg:    '#241c0c',
  historyBorder:    '#5a4a20',
  historyText:      '#e8d8a0',
  historyTextMuted: '#7a6a3a',
  historyGold:      '#e8c84a',
  historyGoldSoft:  '#c8a84a',
  historyRowBg:     '#3a2e14',
  historyRowHover:  '#463818',
  historyAccent:    '#a08040',
  prCardBg:         '#0d2a4a',
  prCardBorder:     '#1d9e75',
  prCardVal:        '#5adb9a',
  prCardLbl:        '#4aab7a',
  eiRowBg:          '#0f2238',
  eiVal:            '#5adb9a',
  drVal:            '#f0f8ff',
  drNote:           '#5a9aaa',
  isPrBg:           '#1c1508',

  // ── Progress screen ───────────────────────────────────────────────────────
  progressBg:       '#071624',
  progressStatusText:'#4a7a9a',
  progressTopH1:    '#7dd8ff',
  chartCardBg:      '#0f2238',
  chartCardBgAlt:   '#0d1e30',
  chartCardBorder:  '#ff6b4a',
  chartCardBorderAlt:'#1e5080',
  chartCardGlow1:   'rgba(74,154,220,0.25)',
  chartCardGlow2:   'rgba(74,154,220,0.12)',
  chartCardGlow3:   'rgba(30,80,128,0.08)',
  chartTitle:       '#8bbdd8',
  chartTitleAlt:    '#7dd8ff',
  sprintCardBg:     '#0f2238',
  sprintDist:       '#f0f8ff',
  sprintPr:         '#5adb9a',
  sprintNone:       '#4a7a9a',
  sprintActiveBg:   '#201a08',
  repWheelActive:   '#00ff88',
  repWheelInactive: '#4a7a9a',
  modalBg:          '#0a1828',

  // ── Graph / Recharts ──────────────────────────────────────────────────────
  graphStroke:      '#00ff88',
  graphFill:        '#00ff88',
  graphDot:         '#00ff88',
  graphDotStroke:   '#071624',
  graphAxis:        '#1e3a55',
  graphAxisTick:    '#4a7a9a',
  graphGrid:        'rgba(74,154,220,0.12)',
  graphTooltipBg:   '#0d1e30',
  graphTooltipBorder:'#1e5080',
  graphBwGrid:      'rgba(255,255,255,0.04)',
  graphBwTick:      '#39e07a',

  // ── Timers screen ─────────────────────────────────────────────────────────
  timersBg:         '#111',
  timersStatusText: '#555',
  timersTabBg:      '#0a0a0a',
  timersTabBorder:  '#2a2a2a',
  timersTabText:    '#555',
  timersTabHover:   '#aaa',
  timersTabActive:  '#e0e0e0',
  timersAccent:     '#ff6b4a',
  timersChipBg:     '#1a1a1a',
  timersChipBorder: '#2a2a2a',
  timersChipText:   '#666',
  timersGreen:      '#4db8ff',
  timersGreenBg:    '#0d2a3a',
  timersGreenBorder:'#1d6e9e',
  timersDotDone:    '#00ff88',
  timersText:       '#e0e0e0',
  timersTextMuted:  '#666',
  timersTextDim:    '#444',
  timersSurface:    '#222',
  timersSurfaceLight:'#333',
  timersSwDisplay:  '#ffffff',

  // ── Diet screen ───────────────────────────────────────────────────────────
  dietRingEmpty:    '#1e3a55',
  dietBg:           '#160d20',
  dietStatusBg:     '#0e0814',
  dietStatusText:   '#7a6a8a',
  dietBorder:       '#4a2d6a',
  dietCardBg:       '#0e0818',
  dietCardBorder:   '#2a1a3a',
  dietPurple:       '#a878f0',
  dietPurpleLight:  '#c8a8ff',
  dietPurpleText:   '#9a7abf',
  dietPurpleDeep:   '#6a3a9a',
  dietPurpleBg:     '#1a0d2a',
  dietPurpleSel:    '#3a1a5a',
  dietPurpleBorder: '#3a1a5a',
  dietText:         '#e8d0ff',
  dietTextMuted:    '#6a4a8a',
  dietTrendCalLine: '#a878f0',
  dietTrendCalDot:  '#c8a8ff',
  dietTrendWtLine:  '#7dff4f',
  dietGoalLine:     '#ff6b4a',

  // Macro colors (used in Diet)
  macroCarbs:       '#f4a261',
  macroFats:        '#ff6b4a',
  macroProtein:     '#7dd8ff',
  macroChol:        '#a78bfa',
  macroSodium:      '#7dff4f',

  // ── Settings screen ───────────────────────────────────────────────────────
  settingsBg:       '#0a0f1a',
  settingsLabel:    '#f0f8ff',
  settingsVal:      '#8bbdd8',
  toggleOnBg:       '#1d9e75',
  toggleOnBorder:   '#00ff88',
  toggleOffBg:      '#1e3a55',
  toggleOffBorder:  '#2a5a7a',

  // ── Splash ────────────────────────────────────────────────────────────────
  splashBg:         '#111',

  // ── Theme picker preview swatches (shown in Settings dropdown) ────────────
  previewSwatches: ['#0a1e30', '#5adb9a', '#ff6b4a', '#4a9adc', '#7dd8ff', '#ffd700'],
  previewLabel:    'Deep navy · green · orange',
};

export const carbonTheme = {
  ...defaultTheme,
  name: 'CARBON',

  // ── App shell ─────────────────────────────────────────────────────────────
  bgApp:            '#0a0a0a',
  bgAppMobile:      '#000000',
  bgPhone:          '#1a1a1a',
  bgPage:           '#000000',
  bgStatusBar:      '#000000',
  bgTopBar:         '#0d0d0d',
  bgNav:            '#0d0d0d',
  bgScroll:         '#000000',

  // ── Cards / surfaces ──────────────────────────────────────────────────────
  bgCard:           '#161616',
  bgCardAlt:        '#111111',
  bgSurface:        '#1e1e1e',
  bgSurfaceRaised:  '#282828',
  bgInput:          '#1e1e1e',
  bgInputDark:      '#111111',
  bgWeekCard:       '#111111',
  bgTopBarWeek:     'rgba(0,0,0,0.97)',

  // ── Borders ───────────────────────────────────────────────────────────────
  borderDefault:    '#2a2a2a',
  borderActive:     '#00ff88',
  borderMuted:      '#1e1e1e',
  borderRaised:     '#333333',
  borderTopBar:     '#00cc66',
  borderPhone:      '#333333',

  // ── Text ──────────────────────────────────────────────────────────────────
  textPrimary:      '#ffffff',
  textSecondary:    '#aaaaaa',
  textMuted:        '#555555',
  textOnAccent:     '#000000',
  textHeading:      '#ffffff',
  textHeadingAlt:   '#ffffff',
  textBright:       '#ffffff',
  textBlack:        '#000',

  // ── Accents ───────────────────────────────────────────────────────────────
  accentGreen:      '#00ff88',
  accentGreenBright:'#00ff88',
  accentGreenNeon:  '#39ff14',
  accentGreenDark:  '#00cc66',
  accentGreenDeep:  '#004d29',
  accentGreenLogo:  '#00ff88',
  accentBlue:       '#00ff88',
  accentBlueLight:  '#88ffcc',
  accentBluePale:   '#ccffe8',
  accentBlueSky:    '#00cc66',
  accentBlueDeep:   '#003322',
  accentOrange:     '#00ff88',
  accentOrangeDark: '#00cc66',
  accentOrangeAmber:'#00ff88',
  accentOrangeGold: '#00cc66',
  accentRed:        '#cc2222',
  accentRedBright:  '#ff4444',
  accentRedDeep:    '#aa0000',
  accentRedSoft:    '#ff6666',
  accentPurple:     '#00ff88',
  accentPurpleLight:'#88ffcc',
  accentPurpleDeep: '#004d29',
  accentGold:       '#00ff88',
  accentGoldWarm:   '#00ff88',

  // ── Buttons ───────────────────────────────────────────────────────────────
  buttonFdeBg:       '#cc0000',
  buttonFdeBgHover:  '#ff2222',
  buttonFdeText:     '#ffffff',
  buttonSecondaryBg: '#1a1a1a',
  buttonSecondaryText:'#aaaaaa',
  buttonGreenBg:     '#003322',
  buttonGreenText:   '#00ff88',
  buttonGreenBorder: '#00cc66',
  buttonSaveBg:      '#00aa55',

  // ── Nav ───────────────────────────────────────────────────────────────────
  navBg:            '#0d0d0d',
  navBorder:        '#00cc66',
  navInactive:      '#555555',
  navHover:         '#ccffe8',
  navActive:        '#00ff88',
  navLabelColor:    'inherit',

  // ── Inputs ────────────────────────────────────────────────────────────────
  inputBg:          '#1e1e1e',
  inputBorder:      '#2a2a2a',
  inputText:        '#f0f0f0',
  inputBorderFocus: '#00ff88',
  inputPlaceholder: '#444444',

  // ── Chips ─────────────────────────────────────────────────────────────────
  chipBg:           '#161616',
  chipBorder:       '#2a2a2a',
  chipText:         '#888888',
  chipBorderHover:  '#00ff88',
  chipTextHover:    '#ccffe8',
  chipActiveBg:     '#003322',
  chipActiveText:   '#00ff88',
  mchipActiveBg:    '#001a11',

  // ── Stat boxes ────────────────────────────────────────────────────────────
  statBoxBg:        '#161616',
  statBoxVal:       '#ffffff',
  statBoxLbl:       '#777777',

  // ── Badges ────────────────────────────────────────────────────────────────
  badgeBg:          '#003322',
  badgeText:        '#00ff88',
  badgeBorder:      '#00cc66',
  prBadgeBg:        '#990000',
  prBadgeText:      '#ffffff',

  // ── Misc common ───────────────────────────────────────────────────────────
  flashText:        '#00ff88',
  emptyText:        '#444444',
  dividerColor:     '#222222',
  backBtn:          '#cc0000',
  sectionLabel:     '#666666',

  // ── Week screen ───────────────────────────────────────────────────────────
  weekBg:           '#000000',
  weekCard:         '#111111',
  weekBorder:       '#2a2a2a',
  dayPillBg:        '#161616',
  dayPillTodayBg:   '#1a0000',
  dayPillTodayBorder:'#cc0000',
  dayPillTodayText: '#ffffff',
  dayLabel:         '#777777',
  dayNum:           '#ffffff',
  dayDot:           '#cc0000',
  exRowBorder:      '#1e1e1e',
  exRowHover:       '#1e1e1e',
  exName:           '#ffffff',
  exSub:            '#777777',
  circuitHeader:    '#00ff88',
  circuitLine:      '#003322',
  logTitle:         '#00ff88',
  fieldLabel:       '#777777',
  prescribedDone:   '#004d29',
  weekArrow:        '#555555',
  selectedDayBorder:'#cc0000',

  // ── History screen ────────────────────────────────────────────────────────
  historyBg:        '#0a0a0a',
  historyStatusBg:  '#000000',
  historyCardBg:    '#141414',
  historyBorder:    '#2a2a2a',
  historyText:      '#ffffff',
  historyTextMuted: '#666666',
  historyGold:      '#00ff88',
  historyGoldSoft:  '#00cc66',
  historyRowBg:     '#1a1a1a',
  historyRowHover:  '#222222',
  historyAccent:    '#cc0000',
  prCardBg:         '#1a0000',
  prCardBorder:     '#990000',
  prCardVal:        '#ff4444',
  prCardLbl:        '#cc0000',
  eiRowBg:          '#161616',
  eiVal:            '#00ff88',
  drVal:            '#f0f0f0',
  drNote:           '#555555',
  isPrBg:           '#001a11',

  // ── Progress screen ───────────────────────────────────────────────────────
  progressBg:       '#000000',
  progressStatusText:'#555555',
  progressTopH1:    '#ffffff',
  chartCardBg:      '#161616',
  chartCardBgAlt:   '#111111',
  chartCardBorder:  '#cc0000',
  chartCardBorderAlt:'#2a2a2a',
  chartCardGlow1:   'rgba(0,255,136,0.12)',
  chartCardGlow2:   'rgba(0,255,136,0.06)',
  chartCardGlow3:   'rgba(0,40,20,0.15)',
  chartTitle:       '#aaaaaa',
  chartTitleAlt:    '#00ff88',
  sprintCardBg:     '#161616',
  sprintDist:       '#f0f0f0',
  sprintPr:         '#00ff88',
  sprintNone:       '#444444',
  sprintActiveBg:   '#001a11',
  repWheelActive:   '#00ff88',
  repWheelInactive: '#333333',
  modalBg:          '#0a0a0a',

  // ── Graph / Recharts ──────────────────────────────────────────────────────
  graphStroke:      '#00ff88',
  graphFill:        '#00ff88',
  graphDot:         '#00ff88',
  graphDotStroke:   '#000000',
  graphAxis:        '#2a2a2a',
  graphAxisTick:    '#555555',
  graphGrid:        'rgba(0,255,136,0.07)',
  graphTooltipBg:   '#111111',
  graphTooltipBorder:'#00cc66',
  graphBwGrid:      'rgba(255,255,255,0.03)',
  graphBwTick:      '#00ff88',

  // ── Timers screen ─────────────────────────────────────────────────────────
  timersBg:         '#000000',
  timersStatusText: '#444444',
  timersTabBg:      '#0a0a0a',
  timersTabBorder:  '#1e1e1e',
  timersTabText:    '#444444',
  timersTabHover:   '#aaaaaa',
  timersTabActive:  '#f0f0f0',
  timersAccent:     '#00ff88',
  timersChipBg:     '#161616',
  timersChipBorder: '#2a2a2a',
  timersChipText:   '#555555',
  timersGreen:      '#00ff88',
  timersGreenBg:    '#001a11',
  timersGreenBorder:'#00cc66',
  timersDotDone:    '#00ff88',
  timersText:       '#e0e0e0',
  timersTextMuted:  '#555555',
  timersTextDim:    '#333333',
  timersSurface:    '#1a1a1a',
  timersSurfaceLight:'#222222',
  timersSwDisplay:  '#ffffff',

  // ── Diet screen ───────────────────────────────────────────────────────────
  dietRingEmpty:    '#333333',
  dietBg:           '#000000',
  dietStatusBg:     '#000000',
  dietStatusText:   '#555555',
  dietBorder:       '#2a2a2a',
  dietCardBg:       '#0d0d0d',
  dietCardBorder:   '#1e1e1e',
  dietPurple:       '#00ff88',
  dietPurpleLight:  '#88ffcc',
  dietPurpleText:   '#00cc66',
  dietPurpleDeep:   '#003322',
  dietPurpleBg:     '#001a11',
  dietPurpleSel:    '#003322',
  dietPurpleBorder: '#003322',
  dietText:         '#e0e0e0',
  dietTextMuted:    '#444444',
  dietTrendCalLine: '#00ff88',
  dietTrendCalDot:  '#88ffcc',
  dietTrendWtLine:  '#39ff14',
  dietGoalLine:     '#00cc66',

  // Macro colors
  macroCarbs:       '#00ff88',
  macroFats:        '#00cc66',
  macroProtein:     '#88ffcc',
  macroChol:        '#39ff14',
  macroSodium:      '#ffffff',

  // ── Settings screen ───────────────────────────────────────────────────────
  settingsBg:       '#000000',
  settingsLabel:    '#f0f0f0',
  settingsVal:      '#888888',
  toggleOnBg:       '#00cc66',
  toggleOnBorder:   '#00ff88',
  toggleOffBg:      '#1e1e1e',
  toggleOffBorder:  '#333333',

  // ── Splash ────────────────────────────────────────────────────────────────
  splashBg:         '#000000',

  // ── Theme picker preview swatches ─────────────────────────────────────────
  previewSwatches: ['#000000', '#1a1a1a', '#cc0000', '#00ff88', '#ffffff', '#ff4444'],
  previewLabel:    'Black · charcoal · red · neon green',
};

export const americanTheme = {
  ...defaultTheme,
  name: 'AMERICAN',

  // ── App shell ─────────────────────────────────────────────────────────────
  bgApp:            '#707070',
  bgAppMobile:      '#4a4a4a',
  bgPhone:          '#787878',
  bgPage:           '#4a4a4a',
  bgStatusBar:      '#252525',
  bgTopBar:         '#222222',
  bgNav:            '#0d1428',
  bgScroll:         '#4a4a4a',

  // ── Cards / surfaces ──────────────────────────────────────────────────────
  bgCard:           '#0f1830',
  bgCardAlt:        '#0a1228',
  bgSurface:        '#162040',
  bgSurfaceRaised:  '#1e2e55',
  bgInput:          '#162040',
  bgInputDark:      '#0a1228',
  bgWeekCard:       '#0a1228',
  bgTopBarWeek:     'rgba(34,34,34,0.97)',

  // ── Borders ───────────────────────────────────────────────────────────────
  borderDefault:    '#1e2e55',
  borderActive:     '#b22234',
  borderMuted:      '#14203a',
  borderRaised:     '#2a3a6a',
  borderTopBar:     '#b22234',
  borderPhone:      '#3a5aaa',

  // ── Text ──────────────────────────────────────────────────────────────────
  textPrimary:      '#ffffff',
  textSecondary:    '#aabbdd',
  textMuted:        '#4a6090',
  textOnAccent:     '#ffffff',
  textHeading:      '#ffffff',
  textHeadingAlt:   '#e8f0ff',
  textBright:       '#ffffff',
  textBlack:        '#000',

  // ── Accents ───────────────────────────────────────────────────────────────
  accentGreen:      '#ffd700',
  accentGreenBright:'#ffd700',
  accentGreenNeon:  '#ffe84d',
  accentGreenDark:  '#ccaa00',
  accentGreenDeep:  '#4a3800',
  accentGreenLogo:  '#ffd700',
  accentBlue:       '#3a7ad8',
  accentBlueLight:  '#7ab8ff',
  accentBluePale:   '#b8d8ff',
  accentBlueSky:    '#5b9bd8',
  accentBlueDeep:   '#1a3a7a',
  accentOrange:     '#b22234',
  accentOrangeDark: '#8c1a28',
  accentOrangeAmber:'#ffd700',
  accentOrangeGold: '#ffd700',
  accentRed:        '#b22234',
  accentRedBright:  '#dc2a3e',
  accentRedDeep:    '#7a0a1a',
  accentRedSoft:    '#e05060',
  accentPurple:     '#7ab8ff',
  accentPurpleLight:'#b8d8ff',
  accentPurpleDeep: '#1a3a7a',
  accentGold:       '#ffd700',
  accentGoldWarm:   '#ffd700',

  // ── Buttons ───────────────────────────────────────────────────────────────
  buttonFdeBg:       '#b22234',
  buttonFdeBgHover:  '#dc2a3e',
  buttonFdeText:     '#ffffff',
  buttonSecondaryBg: '#0f1830',
  buttonSecondaryText:'#aabbdd',
  buttonGreenBg:     '#1a3a7a',
  buttonGreenText:   '#7ab8ff',
  buttonGreenBorder: '#3a7ad8',
  buttonSaveBg:      '#b22234',

  // ── Nav ───────────────────────────────────────────────────────────────────
  navBg:            '#0d1428',
  navBorder:        '#b22234',
  navInactive:      '#aabbdd',
  navHover:         '#ffffff',
  navActive:        '#ffd700',
  navLabelColor:    '#ffffff',

  // ── Inputs ────────────────────────────────────────────────────────────────
  inputBg:          '#162040',
  inputBorder:      '#1e2e55',
  inputText:        '#ffffff',
  inputBorderFocus: '#3a7ad8',
  inputPlaceholder: '#4a6090',

  // ── Chips ─────────────────────────────────────────────────────────────────
  chipBg:           '#0f1830',
  chipBorder:       '#1e2e55',
  chipText:         '#aabbdd',
  chipBorderHover:  '#3a7ad8',
  chipTextHover:    '#b8d8ff',
  chipActiveBg:     '#1a3a7a',
  chipActiveText:   '#7ab8ff',
  mchipActiveBg:    '#1a2a5a',

  // ── Stat boxes ────────────────────────────────────────────────────────────
  statBoxBg:        '#0f1830',
  statBoxVal:       '#ffd700',
  statBoxLbl:       '#aabbdd',

  // ── Badges ────────────────────────────────────────────────────────────────
  badgeBg:          '#1a3a7a',
  badgeText:        '#7ab8ff',
  badgeBorder:      '#3a7ad8',
  prBadgeBg:        '#b22234',
  prBadgeText:      '#ffffff',

  // ── Misc common ───────────────────────────────────────────────────────────
  flashText:        '#ffd700',
  emptyText:        '#4a6090',
  dividerColor:     '#1e2e55',
  backBtn:          '#b22234',
  sectionLabel:     '#b22234',

  // ── Week screen ───────────────────────────────────────────────────────────
  weekBg:           '#4a4a4a',
  weekCard:         '#0a1228',
  weekBorder:       '#1e2e55',
  dayPillBg:        '#0f1830',
  dayPillTodayBg:   '#7a0a1a',
  dayPillTodayBorder:'#b22234',
  dayPillTodayText: '#ffffff',
  dayLabel:         '#4a6090',
  dayNum:           '#ffffff',
  dayDot:           '#b22234',
  exRowBorder:      '#14203a',
  exRowHover:       '#162040',
  exName:           '#ffffff',
  exSub:            '#aabbdd',
  circuitHeader:    '#ffd700',
  circuitLine:      '#4a3800',
  logTitle:         '#ffd700',
  fieldLabel:       '#aabbdd',
  prescribedDone:   '#1a3a7a',
  weekArrow:        '#4a6090',
  selectedDayBorder:'#ffd700',

  // ── History screen ────────────────────────────────────────────────────────
  historyBg:        '#4a4a4a',
  historyStatusBg:  '#000000',
  historyCardBg:    '#0f1830',
  historyBorder:    '#1e2e55',
  historyText:      '#ffffff',
  historyTextMuted: '#4a6090',
  historyGold:      '#ffd700',
  historyGoldSoft:  '#ccaa00',
  historyRowBg:     '#0a1228',
  historyRowHover:  '#162040',
  historyAccent:    '#b22234',
  prCardBg:         '#7a0a1a',
  prCardBorder:     '#b22234',
  prCardVal:        '#ffd700',
  prCardLbl:        '#dc2a3e',
  eiRowBg:          '#0f1830',
  eiVal:            '#ffd700',
  drVal:            '#ffffff',
  drNote:           '#4a6090',
  isPrBg:           '#3a0a14',

  // ── Progress screen ───────────────────────────────────────────────────────
  progressBg:       '#4a4a4a',
  progressStatusText:'#aaaaaa',
  progressTopH1:    '#ffffff',
  chartCardBg:      '#0f1830',
  chartCardBgAlt:   '#0a1228',
  chartCardBorder:  '#b22234',
  chartCardBorderAlt:'#1e2e55',
  chartCardGlow1:   'rgba(178,34,52,0.25)',
  chartCardGlow2:   'rgba(178,34,52,0.12)',
  chartCardGlow3:   'rgba(80,10,20,0.10)',
  chartTitle:       '#ffffff',
  chartTitleAlt:    '#ffffff',
  sprintCardBg:     '#0f1830',
  sprintDist:       '#ffffff',
  sprintPr:         '#ffd700',
  sprintNone:       '#4a6090',
  sprintActiveBg:   '#3a0a14',
  repWheelActive:   '#ffd700',
  repWheelInactive: '#1e2e55',
  modalBg:          '#0a1228',

  // ── Graph / Recharts ──────────────────────────────────────────────────────
  graphStroke:      '#ffd700',
  graphFill:        '#ffd700',
  graphDot:         '#ffd700',
  graphDotStroke:   '#06080f',
  graphAxis:        '#1e2e55',
  graphAxisTick:    '#4a6090',
  graphGrid:        'rgba(58,122,216,0.10)',
  graphTooltipBg:   '#0a1228',
  graphTooltipBorder:'#3a7ad8',
  graphBwGrid:      'rgba(255,255,255,0.04)',
  graphBwTick:      '#ffd700',

  // ── Timers screen ─────────────────────────────────────────────────────────
  timersBg:         '#4a4a4a',
  timersStatusText: '#4a6090',
  timersTabBg:      '#080b18',
  timersTabBorder:  '#1e2e55',
  timersTabText:    '#4a6090',
  timersTabHover:   '#aabbdd',
  timersTabActive:  '#ffffff',
  timersAccent:     '#b22234',
  timersChipBg:     '#0f1830',
  timersChipBorder: '#1e2e55',
  timersChipText:   '#4a6090',
  timersGreen:      '#ffd700',
  timersGreenBg:    '#2a1a00',
  timersGreenBorder:'#ccaa00',
  timersDotDone:    '#ffd700',
  timersText:       '#ffffff',
  timersTextMuted:  '#4a6090',
  timersTextDim:    '#2a3a5a',
  timersSurface:    '#0f1830',
  timersSurfaceLight:'#162040',
  timersSwDisplay:  '#ffffff',

  // ── Diet screen ───────────────────────────────────────────────────────────
  dietRingEmpty:    '#1e2e55',
  dietBg:           '#4a4a4a',
  dietStatusBg:     '#000000',
  dietStatusText:   '#4a6090',
  dietBorder:       '#1e2e55',
  dietCardBg:       '#080b18',
  dietCardBorder:   '#1e2e55',
  dietPurple:       '#7ab8ff',
  dietPurpleLight:  '#b8d8ff',
  dietPurpleText:   '#5b9bd8',
  dietPurpleDeep:   '#1a3a7a',
  dietPurpleBg:     '#0a1a3a',
  dietPurpleSel:    '#1e2e55',
  dietPurpleBorder: '#1e2e55',
  dietText:         '#ffffff',
  dietTextMuted:    '#4a6090',
  dietTrendCalLine: '#b22234',
  dietTrendCalDot:  '#dc2a3e',
  dietTrendWtLine:  '#ffd700',
  dietGoalLine:     '#3a7ad8',

  // Macro colors
  macroCarbs:       '#ffd700',
  macroFats:        '#b22234',
  macroProtein:     '#7ab8ff',
  macroChol:        '#b8d8ff',
  macroSodium:      '#ffffff',

  // ── Settings screen ───────────────────────────────────────────────────────
  settingsBg:       '#4a4a4a',
  settingsLabel:    '#ffffff',
  settingsVal:      '#aabbdd',
  toggleOnBg:       '#b22234',
  toggleOnBorder:   '#dc2a3e',
  toggleOffBg:      '#1e2e55',
  toggleOffBorder:  '#2a3a6a',

  // ── Splash ────────────────────────────────────────────────────────────────
  splashBg:         '#4a4a4a',

  // ── Theme picker preview swatches ─────────────────────────────────────────
  previewSwatches: ['#06080f', '#b22234', '#3a7ad8', '#ffd700', '#7ab8ff', '#ffffff'],
  previewLabel:    'Navy · red · gold · light blue',
};

export const themes = {
  DEFAULT:  defaultTheme,
  CARBON:   carbonTheme,
  AMERICAN: americanTheme,
};

export const THEME_NAMES = Object.keys(themes);
